name: Build Node binaries for macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos-x64:
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        target-node: [14, 16, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn install

      - run: yarn start --node-range node${{ matrix.target-node }} --output dist

      - name: Check if binary is compiled
        id: check_file
        run: |
          (test -f dist/*.sha256sum && echo ::set-output name=EXISTS::true) || echo ::set-output name=EXISTS::false

      - uses: actions/upload-artifact@v2
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-x64
          path: dist/*

  macos-arm:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        target-node: [16, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - name: Setup for Apple Silicon
        run: |
          sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer/
          echo "SDKROOT=$(xcrun -sdk macosx$(sw_vers -productVersion) --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx$(sw_vers -productVersion) --show-sdk-platform-version)" >> $GITHUB_ENV

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install

      - run: yarn start --arch arm64 --node-range node${{ matrix.target-node }} --output dist

      - name: Check if binary is compiled
        id: check_file
        run: |
          (test -f dist/*.sha256sum && echo ::set-output name=EXISTS::true) || echo ::set-output name=EXISTS::false

      - uses: actions/upload-artifact@v2
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-arm64
          path: dist/*
